[versions]
appId = "tmidev.customerbase"
androidApiTarget = "34"
androidApiMin = "21"
buildTools = "34.0.0"
agp = "8.1.1"
java = "17"
kotlin = "1.9.0"
composeCompiler = "1.5.2"
ksp = "1.9.0-1.0.13"
hilt = "2.47"
hiltExt = "1.0.0"
androidCore = "1.10.1"
androidActivity = "1.7.2"
composeBom = "2023.08.00"
accompanist = "0.32.0"
navigation = "2.7.1"
lifecycle = "2.6.1"
coroutines = "1.7.3"
datastore = "1.0.0"
room = "2.5.2"
javaxInject = "1"
junit4 = "4.13.2"
mockito = "5.1.0"
turbine = "1.0.0"

[libraries]
androidx-coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "androidCore" }
androidx-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidActivity" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-animation = { group = "androidx.compose.animation", name = "animation" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-materialIcons = { group = "androidx.compose.material", name = "material-icons-extended" }
accompanist-systemUiController = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
lifecycle-runtimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-androidCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-extCompose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltExt" }
hilt-extCompiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
mockito = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }