name: Unit Test Checkout

on:
  pull_request:
    branches:
      - main

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout_step
        uses: actions/checkout@v3

      - name: Setup JDK
        id: setup_jdk_step
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17

      - name: Setup Gradle
        id: setup_gradle_step
        uses: gradle/gradle-build-action@v2

      # Gradle files created from Windows may require permission, two options to fix:
      # first option is run the following command on your project: git update-index --chmod=+x gradlew
      # second option is to create a step to run every time along with the workflow:
      # - name: Permission to Gradlew
      #   id: permission_gradlew_step
      #   run: chmod +x gradlew

      - name: Run Unit Tests
        id: run_unit_tests_step
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Upload Test Reports
        id: upload_test_reports_step
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Reports
          path: app/build/reports/